"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cnet_answer_t(object):
    __slots__ = ["answer", "command_origin", "correct", "error"]

    def __init__(self):
        self.answer = ""
        self.command_origin = ""
        self.correct = False
        self.error = 0

    def encode(self):
        buf = BytesIO()
        buf.write(cnet_answer_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __answer_encoded = self.answer.encode('utf-8')
        buf.write(struct.pack('>I', len(__answer_encoded)+1))
        buf.write(__answer_encoded)
        buf.write(b"\0")
        __command_origin_encoded = self.command_origin.encode('utf-8')
        buf.write(struct.pack('>I', len(__command_origin_encoded)+1))
        buf.write(__command_origin_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bb", self.correct, self.error))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cnet_answer_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cnet_answer_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cnet_answer_t()
        __answer_len = struct.unpack('>I', buf.read(4))[0]
        self.answer = buf.read(__answer_len)[:-1].decode('utf-8', 'replace')
        __command_origin_len = struct.unpack('>I', buf.read(4))[0]
        self.command_origin = buf.read(__command_origin_len)[:-1].decode('utf-8', 'replace')
        self.correct = bool(struct.unpack('b', buf.read(1))[0])
        self.error = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cnet_answer_t in parents: return 0
        tmphash = (0x10502e133e8e7777) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cnet_answer_t._packed_fingerprint is None:
            cnet_answer_t._packed_fingerprint = struct.pack(">Q", cnet_answer_t._get_hash_recursive([]))
        return cnet_answer_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

